#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo OPENSHIFT_INTERNAL_IP: $OPENSHIFT_INTERNAL_IP
echo OPENSHIFT_GEAR_NAME: $OPENSHIFT_GEAR_NAME
echo OPENSHIFT_GEAR_DIR: $OPENSHIFT_GEAR_DIR
echo OPENSHIFT_DATA_DIR: $OPENSHIFT_DATA_DIR
echo OPENSHIFT_TMP_DIR: $OPENSHIFT_TMP_DIR

cd $OPENSHIFT_GEAR_DIR/repo 
export felixcmd="java -Dorg.ops4j.pax.web.listening.addresses=$OPENSHIFT_INTERNAL_IP -cp $(echo lib/*.jar | tr ' ' ':') com.dexels.navajo.runtime.openshift.OpenshiftFrameworkInstance"
echo "Command Line: $felixcmd"
java -Dorg.ops4j.pax.web.listening.addresses=$OPENSHIFT_INTERNAL_IP -cp $(echo lib/*.jar | tr ' ' ':') com.dexels.navajo.runtime.openshift.OpenshiftFrameworkInstance
#
#java -cp $(echo lib/*.jar | tr ' ' ':')
#nohup $felixcmd &


